;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        comment-dwim
        electric-pair-delete-pair
        kill-region
        yaml-electric-backspace
        yaml-electric-dash-and-dot
        ))

(setq mc/cmds-to-run-once
      '(
        hydra-mc/mc/mark-next-like-this
        hydra-mc/mc/mark-previous-like-this
        hydra-mc/mc/skip-to-previous-like-this
        hydra-mc/mc/unmark-next-like-this
        hydra-mc/mc/unmark-previous-like-this
        ))
