;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        browse-kill-ring
        electric-newline-and-maybe-indent
        electric-pair-delete-pair
        forward-sentence
        forward-sexp
        ivy-wgrep-change-to-wgrep-mode
        mark-sexp
        org-self-insert-command
        wgrep-finish-edit
        yaml-electric-backspace
        yaml-electric-bar-and-angle
        ))

(setq mc/cmds-to-run-once
      '(
        mouse-set-region
        ))
