;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        browse-kill-ring
        easy-kill
        electric-newline-and-maybe-indent
        electric-pair-delete-pair
        forward-sentence
        forward-sexp
        indent-for-tab-command
        ivy-wgrep-change-to-wgrep-mode
        kill-region
        mark-sexp
        org-self-insert-command
        org-yank
        string-inflection-all-cycle
        string-inflection-python-style-cycle
        wgrep-finish-edit
        yaml-electric-backspace
        yaml-electric-bar-and-angle
        ))

(setq mc/cmds-to-run-once
      '(
        mouse-set-region
        ))
