;;; -*- coding: utf-8; lexical-binding: t; -*-

;; Copy from https://github.com/nashamri/spacemacs-theme/blob/master/spacemacs-common.el

(require 'init-face-common)

(setq local/org-agenda-height nil)
(setq local/org-highlight t)
(setq local/org-height nil)
(setq local/org-priority-bold t)
(setq local/org-bold t)

(with-eval-after-load 'org
 (set-face-attribute 'org-agenda-clocking nil :background local-color/highlight :foreground local-color/comp)
 (set-face-attribute 'org-agenda-date nil :foreground local-color/var :height (if local/org-agenda-height 1.1 1.0))
 (set-face-attribute 'org-agenda-date-today nil :foreground local-color/keyword :inherit 'bold :height (if local/org-agenda-height 1.3 1.0))
 (set-face-attribute 'org-agenda-date-weekend nil :inherit 'bold :foreground local-color/var)
 (set-face-attribute 'org-agenda-done nil :foreground local-color/suc :height (if local/org-agenda-height 1.2 1.0))
 (set-face-attribute 'org-agenda-structure nil :inherit 'bold :foreground local-color/comp)
 (set-face-attribute 'org-block nil :background local-color/cblk-bg :foreground local-color/cblk :extend t)
 (set-face-attribute 'org-block-begin-line nil :background local-color/cblk-ln-bg :foreground local-color/cblk-ln :extend t)
 (set-face-attribute 'org-block-end-line nil :background local-color/cblk-ln-bg :foreground local-color/cblk-ln :extend t)
 (set-face-attribute 'org-clock-overlay nil :foreground local-color/comp)
 (set-face-attribute 'org-code nil :foreground local-color/cyan)
 (set-face-attribute 'org-column nil :background local-color/highlight)
 (set-face-attribute 'org-column-title nil :background local-color/highlight)
 (set-face-attribute 'org-date nil :underline t :foreground local-color/var)
 (set-face-attribute 'org-date-selected nil :background local-color/func :foreground local-color/bg1)
 (set-face-attribute 'org-document-info-keyword nil :foreground local-color/meta)
 (set-face-attribute 'org-document-title nil :foreground local-color/func :inherit 'bold :height (if local/org-height 1.4 1.0) :underline t)
 (set-face-attribute 'org-done nil :foreground local-color/suc :inherit 'bold :background local-color/green-bg)
 (set-face-attribute 'org-ellipsis nil :foreground local-color/keyword)
 (set-face-attribute 'org-footnote nil :underline t :foreground local-color/base)
 (set-face-attribute 'org-hide nil :foreground local-color/base)
 (set-face-attribute 'org-level-1 nil :inherit 'bold :bold (if local/org-bold 'unspecified nil) :foreground local-color/head1 :height (if local/org-height 1.3 1.0) :background (when local/org-highlight local-color/head1-bg))
 (set-face-attribute 'org-level-2 nil :inherit 'bold :bold (if local/org-bold 'unspecified nil) :foreground local-color/head2 :height (if local/org-height 1.2 1.0) :background (when local/org-highlight local-color/head2-bg))
 (set-face-attribute 'org-level-3 nil :bold nil :foreground local-color/head3 :height (if local/org-height 1.1 1.0) :background (when local/org-highlight local-color/head3-bg))
 (set-face-attribute 'org-level-4 nil :bold nil :foreground local-color/head4 :background (when local/org-highlight local-color/head4-bg))
 (set-face-attribute 'org-level-5 nil :bold nil :foreground local-color/head1)
 (set-face-attribute 'org-level-6 nil :bold nil :foreground local-color/head2)
 (set-face-attribute 'org-level-7 nil :bold nil :foreground local-color/head3)
 (set-face-attribute 'org-level-8 nil :bold nil :foreground local-color/head4)
 (set-face-attribute 'org-link nil :underline t :foreground local-color/comment)
 (set-face-attribute 'org-meta-line nil :foreground local-color/meta)
 (set-face-attribute 'org-mode-line-clock-overrun nil :foreground local-color/err)
 (set-face-attribute 'org-priority nil :foreground local-color/war :inherit 'bold :bold (if local/org-priority-bold 'unspecified nil))
 (set-face-attribute 'org-quote nil :inherit 'org-block :slant 'italic)
 (set-face-attribute 'org-scheduled nil :foreground local-color/comp)
 (set-face-attribute 'org-scheduled-today nil :foreground local-color/func :height (if local/org-agenda-height 1.2 1.0))
 (set-face-attribute 'org-scheduled-previously nil :foreground local-color/base :slant 'italic)
 (set-face-attribute 'org-sexp-date nil :foreground local-color/base)
 (set-face-attribute 'org-special-keyword nil :foreground local-color/func)
 (set-face-attribute 'org-table nil :foreground local-color/base :background local-color/head1-bg)
 (set-face-attribute 'org-tag nil :foreground local-color/meta)
 (set-face-attribute 'org-time-grid nil :foreground local-color/str)
 (set-face-attribute 'org-todo nil :foreground local-color/war :inherit 'bold :background local-color/yellow-bg)
 (set-face-attribute 'org-upcoming-deadline nil :foreground local-color/war :inherit 'org-priority)
 (set-face-attribute 'org-upcoming-distant-deadline nil :foreground local-color/suc :inherit 'org-priority)
 (set-face-attribute 'org-verbatim nil :foreground local-color/keyword)
 (set-face-attribute 'org-verse nil :inherit 'org-block :slant 'italic)
 (set-face-attribute 'org-warning nil :foreground local-color/err :inherit 'org-priority)
)

(provide 'init-org-face)
