(load-file (expand-file-name "site-lisp/config/init-chatgpt-shell.el" user-emacs-directory))
(load-file (expand-file-name "site-lisp/config/init-copilot.el.el" user-emacs-directory))
(load-file (expand-file-name "site-lisp/config/init-emacs-prisma-mode.el" user-emacs-directory))
(load-file (expand-file-name "site-lisp/config/init-gptel.el" user-emacs-directory))
(load-file (expand-file-name "site-lisp/config/init-nano-theme.el" user-emacs-directory))
(load-file (expand-file-name "site-lisp/config/init-topsy.el.el" user-emacs-directory))
(load-file (expand-file-name "site-lisp/config/init-wrap-region.el.el" user-emacs-directory))