(push (expand-file-name "site-lisp/color-rg" user-emacs-directory) load-path)
(push (expand-file-name "site-lisp/duplicate-line" user-emacs-directory) load-path)
(push (expand-file-name "site-lisp/hydra-posframe" user-emacs-directory) load-path)
(push (expand-file-name "site-lisp/one-key" user-emacs-directory) load-path)
(push (expand-file-name "site-lisp/posframe" user-emacs-directory) load-path)
(push (expand-file-name "site-lisp/thing-edit" user-emacs-directory) load-path)
(push (expand-file-name "site-lisp/toggle-one-window" user-emacs-directory) load-path)